<a href="https://colab.research.google.com/github/UdaraChamidu/Generative-AI/blob/main/keyword_and_semantic_search.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install numpy scikit-learn sentence-transformers -q

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 2.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 19.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 24.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 23.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 2.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 4.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 9.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 8.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 4.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 57.0 MB/s eta 0:00:00


In [3]:
documents = [
    "The T20 World Cup 2024 is in full swing, bringing excitement and drama to cricket fans worldwide.India's team, captained by Rohit Sharma, is preparing for a crucial match against Ireland, with standout player Jasprit Bumrah expected to play a pivotal role in their campaign.The tournament has already seen controversy, particularly concerning the pitch conditions at Nassau County International Cricket Stadium in New York, which came under fire after a low-scoring game between Sri Lanka and South Africa.",
    "The world of football is buzzing with excitement as major tournaments and league matches continue to captivate fans globally.In the UEFA Champions League, the semi-final matchups have been set, with defending champions Real Madrid set to face Manchester City, while Bayern Munich will take on Paris Saint-Germain.Both ties promise thrilling encounters, featuring some of the best talents in world football.",
    "As election season heats up, the latest developments reveal a highly competitive atmosphere across several key races.The presidential election has seen intense campaigning from all major candidates, with recent polls indicating a tight race.Incumbent President Jane Doe is seeking re-election on a platform of economic stability and healthcare reform, while her main rival, Senator John Smith, focuses on education and climate change initiatives.",
    "The AI revolution continues to transform industries and reshape the global economy.Significant advancements in artificial intelligence have led to breakthroughs in healthcare, with AI-driven diagnostics improving patient outcomes and reducing costs.Autonomous systems are becoming increasingly prevalent in logistics and transportation, enhancing efficiency and safety."
]

In [4]:
import re    # regular expression (for some preprocesses of the next text)

def preprocessing(text):
    text = text.lower()  # lowercase
    text = re.sub(r'[^\w\s]', '', text) # punchuation remove ..
    return text # return the text without above ?,! or upercase..

preprocessed_documents = [preprocessing(doc) for doc in documents]

for doc in preprocessed_documents:
    print(doc)

# after that document will return with new look

the t20 world cup 2024 is in full swing bringing excitement and drama to cricket fans worldwideindias team captained by rohit sharma is preparing for a crucial match against ireland with standout player jasprit bumrah expected to play a pivotal role in their campaignthe tournament has already seen controversy particularly concerning the pitch conditions at nassau county international cricket stadium in new york which came under fire after a lowscoring game between sri lanka and south africa
the world of football is buzzing with excitement as major tournaments and league matches continue to captivate fans globallyin the uefa champions league the semifinal matchups have been set with defending champions real madrid set to face manchester city while bayern munich will take on paris saintgermainboth ties promise thrilling encounters featuring some of the best talents in world football
as election season heats up the latest developments reveal a highly competitive atmosphere across several 

In [6]:
test_query = "machine learning is a subset of artificial intelligence"

# here we are finding the best document from above for this query.
# 2 techniques using. keyword search and semantic search

## Keyword Search

In [9]:
from sklearn.feature_extraction.text import TfidfVectorizer # one hot encoding also ok
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

In [8]:
vectorizer = TfidfVectorizer()

In [10]:
sparse_vectors = vectorizer.fit_transform(preprocessed_documents)

# vector values of given document are ok.

In [13]:
sparse_vectors.toarray()

array([[0.11827505, 0.        , 0.        , 0.11827505, 0.11827505,
        0.11827505, 0.        , 0.        , 0.        , 0.11827505,
        0.12344165, 0.        , 0.        , 0.        , 0.11827505,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.11827505, 0.        , 0.11827505, 0.11827505, 0.        ,
        0.11827505, 0.11827505, 0.        , 0.11827505, 0.        ,
        0.11827505, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.11827505, 0.11827505, 0.        ,
        0.        , 0.11827505, 0.        , 0.11827505, 0.23655009,
        0.11827505, 0.11827505, 0.        , 0.        , 0.        ,
        0.        , 0.11827505, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.09324941,
        0.11827505, 0.        , 0.09324941, 0.        , 0.11827505,
        0.        , 0.        , 0.11827505, 0.        , 0.11827505,
        0.11827505, 0.        , 0.        , 0.09

In [14]:
len(sparse_vectors.toarray()[0])

183

In [15]:
test_query_sparse_vector = vectorizer.transform([test_query])

# vector values of given query (input) is ok.

In [ ]:
len(test_query_sparse_vector.toarray()[0])

183

In [18]:
# now we have to compare query vectors and document vectors.
# take good vectors from document vectors which ok for user input vectors
keyword_similarities = cosine_similarity(sparse_vectors, test_query_sparse_vector)

keyword_similarities

# output has 4 values. those 4 for 4 documents. which one has the highest value is the best vector for user input one.
# minimum value is the worst one for the provided query

array([[0.05537393],
       [0.11902777],
       [0.07839555],
       [0.17677653]])

In [19]:
ranked_indexes = np.argsort(keyword_similarities, axis=0)[::-1].flatten()

ranked_indexes

# the rank. 3 rd document is best one, then 1 st one ...

array([3, 1, 2, 0])

In [22]:
ranked_documents = [documents[i] for i in ranked_indexes]

for doc in ranked_documents:
    print(doc)

# places are changed.

The AI revolution continues to transform industries and reshape the global economy.Significant advancements in artificial intelligence have led to breakthroughs in healthcare, with AI-driven diagnostics improving patient outcomes and reducing costs.Autonomous systems are becoming increasingly prevalent in logistics and transportation, enhancing efficiency and safety.
The world of football is buzzing with excitement as major tournaments and league matches continue to captivate fans globally.In the UEFA Champions League, the semi-final matchups have been set, with defending champions Real Madrid set to face Manchester City, while Bayern Munich will take on Paris Saint-Germain.Both ties promise thrilling encounters, featuring some of the best talents in world football.
As election season heats up, the latest developments reveal a highly competitive atmosphere across several key races.The presidential election has seen intense campaigning from all major candidates, with recent polls indica

## Semantic Search

In [23]:
from sklearn.metrics.pairwise import cosine_similarity
from sentence_transformers import SentenceTransformer
import numpy as np

In [24]:
embedding_model = SentenceTransformer('all-MiniLM-L6-v2')

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`


model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [25]:
dense_vectors = embedding_model.encode(preprocessed_documents)
# made the vectors for the semantic search

In [26]:
len(dense_vectors[0])

384

In [27]:
dense_vectors

array([[ 0.03787256,  0.0628797 ,  0.04963027, ..., -0.06947389,
        -0.05075601, -0.01224575],
       [-0.00339274,  0.01953053, -0.00371151, ..., -0.0089168 ,
        -0.0226684 ,  0.03135144],
       [-0.00350871, -0.01150496,  0.07882169, ..., -0.07554866,
         0.02237301,  0.0278266 ],
       [-0.01032217, -0.01923386, -0.02120156, ..., -0.0767002 ,
         0.08044681, -0.09211533]], dtype=float32)

In [28]:
test_query_dense_vector = embedding_model.encode([test_query])

In [30]:
len(test_query_dense_vector[0])  # this model always give size of 384 embedding vectors

384

In [31]:
semantic_similarities = cosine_similarity(dense_vectors, test_query_dense_vector)

semantic_similarities

# last(4) document has more value.

array([[0.0199223 ],
       [0.09100747],
       [0.04911966],
       [0.37954295]], dtype=float32)

In [32]:
ranked_indexes = np.argsort(semantic_similarities, axis=0)[::-1].flatten()

ranked_indexes

array([3, 1, 2, 0])

In [33]:
ranked_documents = [documents[i] for i in ranked_indexes]

for doc in ranked_documents:
    print(doc)

The AI revolution continues to transform industries and reshape the global economy.Significant advancements in artificial intelligence have led to breakthroughs in healthcare, with AI-driven diagnostics improving patient outcomes and reducing costs.Autonomous systems are becoming increasingly prevalent in logistics and transportation, enhancing efficiency and safety.
The world of football is buzzing with excitement as major tournaments and league matches continue to captivate fans globally.In the UEFA Champions League, the semi-final matchups have been set, with defending champions Real Madrid set to face Manchester City, while Bayern Munich will take on Paris Saint-Germain.Both ties promise thrilling encounters, featuring some of the best talents in world football.
As election season heats up, the latest developments reveal a highly competitive atmosphere across several key races.The presidential election has seen intense campaigning from all major candidates, with recent polls indica